### PR TITLE
feat : Updates for issue templates 🛠

### LINKED ISSUE #31: Updates : Issue Templates 🛠
## What i am suggesting to update ? 

I am suggesting to update the Issue templates , currently we are using `.md` files instead of the brand new issue forms with `.yml` files.

## Why to update it ? 

Adding an issue Template allows you to organize the issues made by folks in a much better way.
 - We can know if someone wants to write a test or maybe fix something.
 - The issue template forms makes writing details more efficient
 - We have a `required` tag which makes adding details more efficient !
 - Here's a general idea : 
 
image

image

## Can i work on it ? 

Yes, i will be glad to help an Opensource project grow more !

### PR DESCRIPTION
**Pull request by tamalCodes**
This PR closes #31 

**- What I did**
- Added new `.yml` files as issue templates instead of the previous `.md` files
- Added a new config file with `blank_issues_enabled: true` which enables blank issues
- Removed the old `.md` files

**- How I did it**
I did it by adding the `.yml` files in the `ISSUE_TEMPLATE` directory

**- How to verify it**

Visit the forked version [here](https://github.com/IAmTamal/.github/issues/new/choose)
 and try and make a new issue.

image
image

### CODE REVIEW

**Comment by tamalCodes** [comment]
@cpswan i have added the new templates, for bug, feature based on the old termplates, but what do i do with `Pub.dev checklist` ? 

image

**Comment by cpswan** [comment]
@IAmTamal for the top section where you ask `Do you want these to be input fields?` I think the answer is no, that part is just illustrative.

The bottom section `These can be made checkboxes` absolutely - yes.

**Comment by cpswan** [comment]
I've converted to draft for now. Please convert it back when you think it's ready for review and merge.

**Comment by tamalCodes** [comment]
image

@cpswan  - changes have been made, sorry about being inactive :(

**Review by cpswan — APPROVED** [review]

**Comment by cpswan** [comment]
Thanks @IAmTamal :)

**Pull request merged**
